### PR TITLE
This should fix configuration bug

### PR DESCRIPTION
**Pull request by Guidofaassen**
java.io.IOException: Cannot run program "git": error=2, No such file or directory

### CODE REVIEW

**Comment by fabiankrack** [comment]
Can you please explain why you want to delete those configuraiton lines?
The error message you posted indicates that 'git' is not installed.

**Comment by Guidofaassen** [comment]
A similar problem is listed here: https://groups.google.com/forum/#!searchin/predictionio-user/java.io.IOException$3A$20Cannot$20run$20program$20%22git%22$3A$20error$3D2$2C$20No$20such$20file$20or$20directory/predictionio-user/fY52_thXhAM/hcfqY-lqHtEJ

They mention that the pio-env is not initialized properly. Furthermore, when I tried to run this before with these lines that were there, it didn't work either (can't remember which error I had though). So that's why I think this may solve the issue.

**Comment by fabiankrack** [comment]
Actually i don't think so. Elasticsearch has nothing to do with git.
Could you maybe share an example project to reproduce those errors you see?

**Comment by Guidofaassen** [comment]
Build and run SphereRecommendation/Dockerfile. I added a Git update, but didn't work. Error is thrown when calling "pio build".

**Comment by fabiankrack** [comment]
Please keep in mind that this is a public repository, so all conversations are also public.
If you base your docker container on sphereio/predictionio and run "git update" inside, you should probably install git in your container, e.g. via

`RUN apt-get install -y git`

**Comment by Guidofaassen** [comment]
Thanks for the hint, that solved the issue.

**Pull request closed without merging**
